# Credit: https://github.com/deviantony/docker-elk
# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>